
-- CREATE SEQUENCE	

CREATE SEQUENCE category_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE sub_category_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE product_image_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE purchase_order_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE purchase_order_detail_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE member_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE member_status_id_seq
START WITH 0
MINVALUE 0;

CREATE SEQUENCE tag_id_seq
START WITH 0
MINVALUE 0;
